baseURL = 'https://gu707.github.io/santa-igreja/'
languageCode = 'pt-br'
title = 'Salve Maria!'
paginate = 5
theme = "paper"
DefaultContentLanguage = "pt-br"

# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456


[params]
  color = 'linen'

  github = 'gu707'
  instagram = 'gugaj4coree'

avatar = ''
  name = 'Gustavo Silva Araujo'
  bio = 'Tenho a alegria de criar esse blogue para compartilhar com todos que desejam aprender sobre a nossa santa igraja catolica.'
